[platformio]
src_dir = .
include_dir = .

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/pedvide/ADC.git
    https://github.com/JonHub/Filters.git
    https://github.com/tonton81/FlexCAN_T4.git
build_flags =
    -D TEENSY41_PORT=1
    -D SERIALCONSOLE=Serial
